spring:
  datasource:
    url: jdbc:mysql://localhost:3306/classificados_amac?useTimezone=true&serverTimezone=UTC
    username: root
    password: 8183

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true